config/routes.rb
Rails.application.routes.draw do
  devise_for :user, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification'
  }

  resources :profile, only: [:show, :edit, :update] do
    member do
      put 'update_password'
    end
  end

  resources :categories, except: [:index] do
    resources :bookmarks

    post 'sub', on: :collection
  end

  root 'home#index'
end

app/models/bookmark.rb
require 'open-uri'

class Bookmark < ActiveRecord::Base
  default_scope { order('created_at desc') }
  scope :broadcasts, -> { where(broadcast: true).order('created_at desc') }
  scope :privates, -> { where(private: true).order('created_at desc') }
  scope :publics, -> { where(public: true).order('created_at desc') }

  belongs_to :category
  belongs_to :user

  validates :url, presence: true
  validates :url, format: { with: URI.regexp }, if: Proc.new { |a| a.url.present? }

  serialize :preview, Array

  paginates_per 16

  def self.for_category(category, page = 0, user = nil)
    where(category: category, user: user).page(page)
  end

  def url_name
    url.gsub('http://', '') || url.gsub('https://', '')
  end

  def title
    super.blank? ? site_name : super
  end

  def parse_url!
    thumbnailer = LinkScraper::Thumbnailer.parse_url!(url)
    self.title = thumbnailer.title
    self.description = thumbnailer.description
    self.site_name = thumbnailer.site_name
    self.video = thumbnailer.video
    self.page_type = thumbnailer.page_type
    self.icon = thumbnailer.icon
    self.preview = thumbnailer.images
    self
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_filter :set_bookmark, only: [:show, :update, :edit, :destroy]

  def index
  end

  def new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @category = Category.find(params[:category_id])
    @bookmark.category = @category
    @bookmark.user = current_user
    authorize! :manage, @bookmark

    if @bookmark.valid?
      @bookmark.parse_url!
      @bookmark.save
    end
  end

  def show
    authorize! :read, @bookmark
  end

  def edit
    authorize! :manage, @bookmark
    @categories = Category.where(user: current_user)
  end

  def update
    authorize! :manage, @bookmark
    @bookmark.assign_attributes(bookmark_params)
    @bookmark.save
  end

  def destroy
    authorize! :manage, @bookmark
    @bookmark.destroy
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find params[:id]
  end

  def bookmark_params
    params.require(:bookmark).permit(:url, :private, :public, :broadcast, :title, :description, :site_name, :category_id)
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmark.html.slim
.bookmark-panel id="bookmark-#{bookmark.id}"
  - if bookmark.user == current_user
    .bookmark-actions
      .pull-right
        .btn-group
          = link_to edit_category_bookmark_path(bookmark.category, bookmark), class: 'btn btn-default btn-sm' do
            span.ion-edit
          = button_to category_bookmark_path(bookmark.category, bookmark), method: 'delete', remote: true, class: 'btn btn-default btn-sm',  data: { disable_with: '...' } do
           span.ion-close-circled
  .bookmark-header
    = link_to category_bookmark_path(bookmark.category, bookmark), title: bookmark.title.humanize, class: 'direct-link' do
      = bookmark.title.humanize
    - if bookmark.icon
      = image_tag(bookmark.icon, class: 'bookmark-icon')
  .bookmark-body class=bookmark.page_type
    = render partial: "bookmarks/#{bookmark.page_type}", locals: { bookmark: bookmark }
    = timeago_tag bookmark.created_at, :nojs => true, :limit => 10.days.ago

app/views/bookmarks/_edit_form.html.slim
.panel.panel-default
  .panel-heading
    h4
      = @bookmark.title
  = simple_form_for([@bookmark.category, @bookmark], remote: true) do |f|
    .panel-body
        = f.input :title
        = f.input :description
        = f.input :site_name
        = f.input :url, as: :string, required: false, autofocus: true, input_html: { placeholder: 'COPY AND PASTE URL HERE' }
        = f.input :category_id, collection: @categories.map {|c| ["#{c.parent.name} -> #{c.name}", c.id]}, selected: @bookmark.category.id
        = f.input :private, as: :boolean, wrapper_html: { class: 'btn checkbox-btn mL5' }, label: '<span>PRIVATE (SAVE)</span>'.html_safe
        = f.input :public, as: :boolean, wrapper_html: { class: 'btn checkbox-btn mL5' }, label: '<span>PUBLIC (SHARE)</span>'.html_safe
        = f.input :broadcast, as: :boolean, wrapper_html: { class: 'btn checkbox-btn mL5' }, label: '<span>BROADCAST (POST)</span>'.html_safe
    .panel-footer
      = f.button :submit, 'UPDATE', class: 'btn btn-navy-blue btn-block mL5', data: { disable_with: 'UPDATING...' }

app/views/bookmarks/_form.html.slim
= simple_form_for([@sub_category || @parent_category || @category, @bookmark], remote: true) do |f|
  .input-group
    = f.input :url, as: :string, required: false, autofocus: true, input_html: { placeholder: 'COPY AND PASTE URL HERE' }, label: false
    .input-group-btn
      = f.input :private, as: :boolean, wrapper_html: { class: 'btn checkbox-btn mL5' }, label: '<span>SAVE</span>'.html_safe
      = f.input :public, as: :boolean, wrapper_html: { class: 'btn checkbox-btn mL5' }, label: '<span>SHARE</span>'.html_safe
      = f.input :broadcast, as: :boolean, wrapper_html: { class: 'btn checkbox-btn mL5' }, label: '<span>POST</span>'.html_safe
      = f.button :submit, 'DO IT', class: 'btn btn-navy-blue mL5', data: { disable_with: 'DOING IT...' }

app/views/bookmarks/_preview.html.slim
- if bookmark.preview.present? && !bookmark.preview.empty?
  .carousel.slide data-ride='carousel' id="bookmark-slide-#{bookmark.id}" data-interval='100000'
    / Slides
    = link_to bookmark.url, target: '_blank', title: bookmark.title do
      .carousel-inner role='listbox'
        - bookmark.preview.each_with_index do |p, i|
          .item class="#{i==0 ? 'active' : nil}"
            = image_tag(p)
    / Controls
    - if bookmark.preview.size > 1
      .slide-controls
        .clearfix
          .pull-left
            = link_to "#bookmark-slide-#{bookmark.id}", class: 'left label label-primary mR10', role: 'button', data: { slide: 'prev' } do
              span.ion-arrow-left-b
              span.sr-only Prev
          .pull-right
            = link_to "#bookmark-slide-#{bookmark.id}", class: 'right label label-primary', role: 'button', data: { slide: 'next' } do
              span.ion-arrow-right-b
              span.sr-only Next
- else
  = link_to bookmark.url, target: '_blank', title: bookmark.title do
    p.no-preview.text-center No Preview

app/views/bookmarks/_video.html.slim
/ Preview
.bookmark-preview
  - if bookmark.video.present? && !bookmark.video.empty?
    iframe class="youtube-player" src="#{bookmark.video}" title="YouTube video player" frameborder="0" height="390" width="100%" allowfullscreen=''
  - else
    / Preview
    = render partial: 'bookmarks/preview', locals: { bookmark: bookmark }

.box.box-default
  .box-body
    = link_to category_bookmark_path(bookmark.category, bookmark), target: '_blank', title: bookmark.title, class: 'bookmark-site-link' do
      span
        = bookmark.title.humanize
    = link_to bookmark.url, target: '_blank', title: bookmark.title, class: 'bookmark-link' do
      span
        = bookmark.site_name
      / Description
      - if bookmark.description.present?
        p title=bookmark.description
          small
            = bookmark.description

app/views/bookmarks/_website.html.slim
/ Preview
.bookmark-preview
  = render partial: 'bookmarks/preview', locals: { bookmark: bookmark }

.box.box-default
  .box-body
    - if bookmark.title.present?
      = link_to category_bookmark_path(bookmark.category, bookmark), target: '_blank', title: bookmark.title, class: 'bookmark-site-link' do
        span
          = bookmark.title.humanize
      = link_to bookmark.url, target: '_blank', title: bookmark.title, class: 'bookmark-link' do
        span
          = bookmark.site_name
        p title=bookmark.description
          small
            = bookmark.description

app/views/bookmarks/create.js.erb
<% if @bookmark.errors.empty? %>
$('#category-link-list-<%= @category.id %>').prepend('<%= escape_javascript(render @bookmark) %>')
$('time').timeago()
<% @bookmark = Bookmark.new %>
<% end %>
$('.new-bookmark-form').html('<%= escape_javascript(render "form") %>')

app/views/bookmarks/destroy.js.erb
<% if @bookmark.errors.empty? %>
  $('#bookmark-<%= @bookmark.id %>').remove()
<% end %>

app/views/bookmarks/edit.html.slim
.row.mT30
  .col-sm-6.col-sm-offset-3
    .btn-group
      = link_to :back, class: 'btn btn-default' do
        span.ion-arrow-left-a.mR10
        span Back
      = link_to category_bookmark_path(@bookmark.category, @bookmark), class: 'btn btn-default' do
        span.ion-arrow-right-a.mR10
        span View
  .col-sm-6.col-sm-offset-3#edit-bookmark.mT10
    = render 'edit_form'

app/views/bookmarks/show.html.slim
.row.mT30
  .col-sm-6.col-sm-offset-3
    .btn-group
      = link_to :back, class: 'btn btn-default' do
        span.ion-arrow-left-a.mR10
        span Back
      - if @bookmark.user == current_user
        = link_to edit_category_bookmark_path(@bookmark.category, @bookmark), class: 'btn btn-default' do
          span.ion-edit.mR10
          span Edit
  .col-sm-6.col-sm-offset-3
    .previews.previews-block-view
      = render @bookmark

app/views/bookmarks/update.js.erb
<% if @bookmark.errors.empty? %>
  _m.render_success('Successfully Updated <%= @bookmark.title %>')
  Turbolinks.visit('<%= category_bookmark_path(@bookmark.category, @bookmark) %>')
<% else %>
  $('#edit-bookmark').html('<%= escape_javascript(render "edit_form") %>')
<% end %>