config/routes.rb
Rails.application.routes.draw do
  devise_for :user, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification'
  }

  resources :profile, only: [:show, :edit, :update] do
    member do
      put 'update_password'
    end
  end

  resources :categories, except: [:index] do
    resources :bookmarks

    post 'sub', on: :collection
  end

  root 'home#index'
end

app/views/shared/_flash.html.slim
- flash.delete(:timedout).each do |k, v|
  .alert.alert-dismissible class="alert-#{k} mT10" role='alert'
    button.close type='button' data-dismiss='alert' aria-label='Close'
      span aria-hidden='true' &times;
    = v

app/views/shared/_header.html.slim
header.header
  .main-navigation
    = link_to '#', class: 'logo' do
      span UNIVERSE
    nav.navbar role='navigation'
      div.navbar-right
        ul.nav.navbar-nav
          li
            = link_to 'HOME', '#', title: 'Home'
          li
            = link_to 'FRIENDS', '#', title: 'Friends'
          li
            = link_to 'PROFILE', edit_profile_path(current_user), title: 'Profile'
          li.logout data-no-turbolink=''
            = link_to destroy_user_session_path, title: 'Logout' do
              span.ion-log-out
  .secondary-navigation
    nav.navbar role='navigation'
      ul.nav.navbar-nav
          li
            = main_nav_category_link_to(Category.shoe_box)
          li
            = main_nav_category_link_to(Category.favorites)
          li
            = main_nav_category_link_to(Category.top_10)
          li
            = main_nav_category_link_to(Category.desert_island)
          li
            = link_to '( THE UNIVERSE )', root_path, class: 'the-universe-link'
          li
            = main_nav_category_link_to(Category.guilty_pleasures)
          li
            = main_nav_category_link_to(Category.projects)
          li
            = main_nav_category_link_to(Category.bucket_list)
          li
            = main_nav_category_link_to(Category.shop)

app/views/shared/_page_limiter.html.slim
select#page_limit.form-control
  option
  - [30, 50, 100].each do |p|
    option value=p href=url_for(params.merge({limit: p}))
      = p

app/views/shared/_preview_buttons.html.slim
.btn-group
  = link_to params.merge({view: 'grid-view'}), class: "btn btn-default #{params[:view] == 'grid-view' || params[:view].nil? ? 'active' : nil}" do
    span.glyphicon.glyphicon-th
  = link_to params.merge({view: 'list-grid-view'}), class: "btn btn-default #{params[:view] == 'list-grid-view' ? 'active' : nil}" do
    span.glyphicon.glyphicon-th-list
  = link_to params.merge({view: 'block-view'}), class: "btn btn-default #{params[:view] == 'block-view' ? 'active' : nil}" do
    span.glyphicon.glyphicon-picture