config/routes.rb
Rails.application.routes.draw do
  devise_for :user, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'password',
    confirmation: 'verification'
  }

  resources :profile, only: [:show, :edit, :update] do
    member do
      put 'update_password'
    end
  end

  resources :categories, except: [:index] do
    resources :bookmarks

    post 'sub', on: :collection
  end

  root 'home#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId

  MAIN = ['Shoe Box', 'Guilty Pleasures', 'Desert Island', 'Shop', 'Top 10', 'Favorites', 'Bucket List', 'Projects']
  PRECREATED = ['Movies', 'Music', 'Books', 'Videos', 'Websites']

  belongs_to :user
  belongs_to :parent, class_name: 'Category', foreign_key: 'parent_id'
  has_many :bookmarks, dependent: :destroy
  has_many :childrens, class_name: 'Category', foreign_key: 'parent_id', dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: { scope: [:parent_id, :user_id] }
  friendly_id :slug_candidates, use: [:history]

  MAIN.each do |category|
    define_singleton_method "#{category.gsub(' ', '_').underscore}" do
      find_by(name: category, default: true, parent: 0, user_id: nil)
    end

    define_singleton_method "#{category.gsub(' ', '_').underscore}?" do
      category.gsub(' ', '_').underscore
    end
  end

  def slug_candidates
    [
      :name,
      [:name, :id],
      [:name, :id, :user_id]
    ]
  end

  def self.main_defaults
    where(parent_id: 0, default: true, user_id: nil)
  end

  def self.generate_precreated(user)
    main_defaults.each do |main_category|
      precreated = PRECREATED.map {|p| { name: p, parent: main_category, user: user } }
      create(precreated)
    end
  end

  def childrens(user = nil)
    if user
      Category.where(parent: self, user: user)
    else
      super
    end
  end

  def find_by_name_and_user(category_name, user)
    Category.find_by(name: category_name, user: user, parent: self)
  end

  def self.find_for_user(category_id, user)
    find_by(id: category_id, user: user)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :set_category, only: [:edit, :update, :destroy]
  helper_method :query_category_params

  def new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    authorize! :manage, @category
    if @category.valid?
      @category.save
      @default_category = @category.parent
    end
  end

  def sub
    @child_category = Category.new(category_params)
    @child_category.user = current_user

    authorize! :manage, @child_category
    if @child_category.valid?
      @child_category.save
      @parent_category = @child_category.parent
    end
  end

  def show
    @default_category = Category.find params[:id]
    @categories = @default_category.childrens(current_user)
    @parent_category = @default_category.find_by_name_and_user(params[:category], current_user) if params[:category] && @default_category
    @sub_category = @parent_category.find_by_name_and_user(params[:sub_category], current_user) if params[:sub_category] && @parent_category
    @sub_categories = @parent_category.childrens(current_user) if @parent_category

    authorize! :read, @sub_category || @parent_category if @sub_category || @parent_category
    @category = Category.new
    @child_category = Category.new
    @bookmark = Bookmark.new
    @bookmarks = []

    if @sub_category
      @bookmarks = Bookmark.for_category(@sub_category, params[:page], current_user).per(params[:limit])
    elsif @parent_category
      @bookmarks = Bookmark.for_category(@parent_category, params[:page], current_user).per(params[:limit])
    end

    gon.params = query_category_params
  end

  def edit
    authorize! :manage, @category
  end

  def update
    authorize! :manage, @category
    @category.assign_attributes(category_params)
    @category.save
  end

  def destroy
    @category.destroy
  end

  private

  def query_category_params
    { default: params[:id], category: params[:category], sub_category: params[:sub_category] }
  end

  def set_category
    @category = Category.find params[:id]
  end

  def category_params
    params.require(:category).permit(:name, :description, :parent_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def main_nav_category_link_to(category)
    link_to category.name.upcase, category_path(category, default: 1, category: params[:category], sub_category: params[:sub_category]), class: 'main-category', data: { default_category: category.to_param }, title: category.name
  end

  def category_link_to(category)
    link_to category.name.humanize, category_path(category.parent, category: params[:category] == category.name ? nil : category.name, sub_category: params[:sub_category]), class: 'btn btn-sm btn-default', data: { category: category.name }
  end

  def sub_category_link_to(category)
    if category.parent.parent
      link_to category.name.humanize, category_path(category.parent.parent, category: category.parent.name, sub_category: params[:sub_category] == category.name ? nil : category.name), class: 'btn btn-sm btn-default', data: { sub_category: category.name }
    end
  end
end

app/views/categories/_category.html.slim
tr id="category-#{category.id}"
  td
    = link_to category.name, category_path(category)
  td
    - if category.user == current_user
      = button_to category_path(category), method: 'delete', remote: true, class: 'btn btn-danger btn-sm', data: { disable_with: 'Loading...' } do
        span DELETE

app/views/categories/_category_form.html.slim
= simple_form_for(@category, remote: true) do |f|
  = f.input :name, required: true, autofocus: true
  = f.hidden_field :parent_id, value: @category.parent_id || @default_category.id
  = f.button :submit, 'Save', class: 'btn-block btn-default-dark btn-sm', data: { disable_with: 'Saving...' }

app/views/categories/_category_form_modal.html.slim
.modal.fade.modal-default id="category-modal#{@category.id}" role='dialog' tabindex='-1'
  .modal-dialog.default-position role='document'
    .modal-content
      .modal-body
        = render 'category_form'

app/views/categories/_sidebar_category.html.slim
.btn-floating-group.sidebar-item.sidebar-category id="sidebar-category-#{cat.id}"
  .clearfix
    = render partial: 'sidebar_hidden_actions', locals: { cat: cat }
    = category_link_to(cat)

app/views/categories/_sidebar_hidden_actions.html.slim
= button_to edit_category_path(cat, format: :js), class: 'btn-action edit-category hidden-action', method: :get, remote: true do
  span.ion-edit
= button_to category_path(cat, format: :js), class: 'btn-action delete-category hidden-action', method: :delete, remote: true do
  span.ion-close-circled

app/views/categories/_sub_category.html.slim
.btn-floating-group.btn-sub-category id="sub-category-#{cat.id}"
  .hidden-actions.clearfix
    = render partial: 'sidebar_hidden_actions', locals: { cat: cat }
  = sub_category_link_to(cat)

app/views/categories/_sub_category_form.html.slim
= simple_form_for(@child_category, remote: true, url: sub_categories_path) do |f|
  = f.input :name, required: true, autofocus: true
  = f.hidden_field :parent_id, value: @child_category.parent_id || @parent_category.id
  = f.button :submit, 'Save', class: 'btn-block btn-default-dark btn-sm', data: { disable_with: 'Saving...' }

app/views/categories/_sub_category_form_modal.html.slim
.modal.fade.modal-default#sub-category-modal role='dialog' tabindex='-1'
  .modal-dialog.default-position role='document'
    .modal-content
      .modal-body
        = render 'sub_category_form'

app/views/categories/create.js.erb
<% if @category.errors.empty? %>
  $('#main-categories .jspPane').append('<%= escape_javascript(render partial: "sidebar_category", locals: { cat: @category }) %>')
  $('#category-modal').modal('hide')
  sidebar()
  <% @category = Category.new %>
<% end %>
$('#category-modal .modal-body').html('<%= escape_javascript(render "category_form") %>')

app/views/categories/destroy.js.erb
<% if @category.errors.empty? %>
  var parentCategory = $('div#sidebar-category-<%= @category.id %>')
  var subCategory = $('div#sub-category-<%= @category.id %>')

  if (parentCategory.length == 1) {
    parentCategory.remove()
    sidebar()
  }

  <% if @category.parent.parent %>
    if(subCategory.length == 1) {
      subCategory.remove()
      Turbolinks.visit('<%= category_path(@category.parent.parent, category: @category.parent.name)%>')
    }
  <% end %>
<% end %>

app/views/categories/edit.js.erb
$('#modal-holder').html('<%= escape_javascript(render "category_form_modal") %>')
$('#category-modal<%= @category.id %>').modal('show')

app/views/categories/show.html.slim
.sidebar-toggle
  = link_to '#', class: 'btn btn-default btn-sm' do
    span.ion-navicon-round
.sidebar.pL10
  .new-category-form
    .sidebar-item
      = link_to '#', class: 'btn btn-sm btn-default', data: { toggle: 'modal', target: '#category-modal' } do
        span.ion-plus-round
        span.mL5 ADD CATEGORY
  #main-categories
    - unless @categories.empty?
      - @categories.each do |cat|
        = render partial: 'sidebar_category', locals: { cat: cat }

#main-content
  - if @parent_category
    .sub-categories-container.clearfix
      .category-actions
        = link_to '#', class: 'btn btn-sm btn-default btn-block', data: { toggle: 'modal', target: '#sub-category-modal'} do
          span.ion-plus-round
          span.mL5 ADD SUB CATEGORY
        = render 'shared/preview_buttons'
      .category-list
        - if @sub_categories
          - @sub_categories.each do |cat|
            = render partial: 'sub_category', locals: { cat: cat }
    / Bookmark field
    .new-bookmark-form.mT30.clearfix
      = render 'bookmarks/form'

    / links
    .link-list-container.previews.clearfix.mT20 id="category-link-list-#{@sub_category.try(:id) || @parent_category.try(:id)}" class="#{params[:view] ? "previews-#{params[:view]}" : 'previews-grid-view'}"
      - unless @bookmarks.empty?
        = render @bookmarks
    - unless @bookmarks.empty?
      .clearfix.mT20
        - if @bookmarks.total_pages > 1
          = render 'shared/page_limiter'
        = paginate @bookmarks
    = render 'sub_category_form_modal'
#modal-holder
= render 'category_form_modal'

app/views/categories/sub.js.erb
<% if @child_category.errors.empty? %>
  $('.category-list').append('<%= escape_javascript(render partial: "sub_category", locals: { cat: @child_category }) %>')
  $('#sub-category-modal').modal('hide')
  <% @child_category = Category.new %>
<% end %>
$('#sub-category-modal .modal-body').html('<%= escape_javascript(render "sub_category_form") %>')

app/views/categories/update.js.erb
<% if @category.errors.empty? %>
  $('div#sidebar-category-<%= @category.id %>').replaceWith('<%= escape_javascript(render partial: 'sidebar_category', locals: { cat: @category }) %>')
  $('div#sub-category-<%= @category.id %>').replaceWith('<%= escape_javascript(render partial: 'sub_category', locals: { cat: @category }) %>')
  $('#category-modal<%= @category.id %>').modal('hide')
  setActiveCategories()
<% else %>
  $('#category-modal<%= @category.id %> .modal-body').html('<%= escape_javascript(render "category_form") %>')
<% end %>